version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3304:3306'
    environment:
      MYSQL_ROOT_PASSWORD: xt87464579
      MYSQL_DATABASE: test
  nestjs:
    image: node:alpine
    ports:
      - '8083:3000'
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app/dist
    command: node main.js
